import Head from 'next/head'

import styles from 'styles/Home.module.css'

import { getVideos } from 'lib/videos'

import NavBar from 'components/Nav/Navbar'
import Banner from 'components/Banner/Banner'
import SectionCards from 'components/Card/SectionCards'

export default function Home({ disneyVideos }) {
   return (
      <div className={styles.container}>
         <Head>
            <title>Netflix</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <NavBar username="nenad@gmail.com" />
         <Banner
            title="Clifford the red dog"
            subTitle="a very cute dog"
            imgUrl="/static/clifford.jpg"
         />
         <div className={styles.sectionWrapper}>
            <SectionCards title="Disney" videos={disneyVideos} size="large" />
            <SectionCards title="Productivity" videos={disneyVideos} size="medium" />
            <SectionCards title="Athletics" videos={disneyVideos} size="small" />
         </div>
      </div>
   )
}

export async function getServerSideProps() {
   const disneyVideos = await getVideos()

   return {
      props: { disneyVideos },
   }
}
