import Head from 'next/head'

import styles from 'styles/Home.module.css'

import { getVideos, getPopularVideos } from 'lib/videos'

import NavBar from 'components/Nav/Navbar'
import Banner from 'components/Banner/Banner'
import SectionCards from 'components/Card/SectionCards'
import { startFetchMyQuery } from 'lib/db/hasura'

export default function Home({ disneyVideos, travelVideos, productivityVideos, popularVideos }) {
   startFetchMyQuery()
   return (
      <div className={styles.container}>
         <Head>
            <title>Netflix</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <div className={styles.main}>
            <NavBar />
            <Banner
               title="Clifford the red dog"
               subTitle="a very cute dog"
               imgUrl="/static/clifford.jpg"
               videoId="4zH5iYM4wJo"
            />
            <div className={styles.sectionWrapper}>
               <SectionCards title="Disney" videos={disneyVideos} size="large" />
               <SectionCards title="Travel" videos={travelVideos} size="medium" />
               <SectionCards title="Productivity" videos={productivityVideos} size="small" />
               <SectionCards title="Popular" videos={popularVideos} size="small" />
            </div>
         </div>
      </div>
   )
}

export async function getServerSideProps() {
   const disneyVideos = await getVideos('disney trailer')
   const travelVideos = await getVideos('travel')
   const productivityVideos = await getVideos('productivity')

   const popularVideos = await getPopularVideos()

   return {
      props: { disneyVideos, travelVideos, productivityVideos, popularVideos },
   }
}
