name: CI

on: [push]:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - develop

jobs:
  standard-checks:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install packages
        run: yarn
      - name: Run ESlint
        run: yarn ci:eslint
      - name: Bundle and Output
        run: yarn build